version: "3"
services:
  # redis-server:
  #   image: redis:alpine
  #   command: redis-server --port 6379
  #   container_name: recordly_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  redis-server:
    image: redis

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "8080:8080"
